name: Python CI

## Trigger the workflow on any push to the main branch or pull request :
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    ## Step 1: Check out the code from the repository    
    - uses: actions/checkout@v4
      name: Check out code 

    ## Step 2: Step up Python environment   
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    ## Step 3: Install dependencies
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
       
    ## Step 3: Run tests 
    - name: Test with pytest
      run: |
        pytest
